<script setup>
defineProps({ compact: { type: Boolean, default: false } })
</script>

<template>
  <div class="delivery-scene" :class="{ 'delivery-scene--compact': compact }" aria-hidden="true">
    <div class="scene-glow"></div><div class="route route--back"></div><div class="route route--front"></div>
    <div class="location location--start"><span></span></div><div class="location location--end"><i class="fas fa-house"></i></div>
    <div class="parcel-shadow"></div>
    <div class="parcel"><div class="parcel__top"><span></span></div><div class="parcel__front"><b>Z</b><em>ON THE WAY</em></div><div class="parcel__side"></div></div>
    <div class="spark spark--one"></div><div class="spark spark--two"></div><div class="spark spark--three"></div>
  </div>
</template>

<style scoped>
.delivery-scene { --scene-size: min(28rem, 82vw); position: relative; width: var(--scene-size); height: calc(var(--scene-size) * .7); margin: 0 auto; perspective: 900px; isolation: isolate; }
.scene-glow { position: absolute; width: 72%; aspect-ratio: 1; left: 16%; top: 8%; border-radius: 50%; background: radial-gradient(circle, rgba(88,219,255,.35), rgba(23,61,237,.08) 48%, transparent 70%); filter: blur(10px); animation: breathe 5s ease-in-out infinite; }
.route { position: absolute; height: 27%; width: 72%; left: 13%; bottom: 18%; border-radius: 50%; transform: rotate(-8deg) skewX(-17deg); }.route--back { border: 2px dashed rgba(171,225,250,.42); }.route--front { border: 3px solid transparent; border-bottom-color: var(--color-accent); box-shadow: 0 8px 12px rgba(23,61,237,.18); }
.location { position: absolute; display: grid; place-items: center; border-radius: 50%; z-index: 2; }.location--start { width: 1.2rem; height: 1.2rem; left: 13%; bottom: 27%; background: var(--color-accent); box-shadow: 0 0 0 7px rgba(23,61,237,.14); animation: pulse 2.2s ease-out infinite; }.location--start span { width: .35rem; height: .35rem; background: white; border-radius: inherit; }.location--end { width: 2.4rem; height: 2.4rem; right: 10%; bottom: 26%; color: var(--color-ink); background: white; box-shadow: 0 7px 18px rgba(5,16,66,.2); font-size: .9rem; }
.parcel-shadow { position: absolute; width: 38%; height: 9%; left: 31%; bottom: 20%; border-radius: 50%; background: rgba(1,8,38,.35); filter: blur(10px); transform: rotateX(67deg); animation: shadow-float 4s ease-in-out infinite; }.parcel { position: absolute; width: 34%; aspect-ratio: 1; left: 33%; top: 20%; transform-style: preserve-3d; transform: rotateX(-13deg) rotateY(-29deg) rotateZ(8deg); animation: parcel-float 4s ease-in-out infinite; }.parcel__top,.parcel__front,.parcel__side { position: absolute; inset: 0; }.parcel__top { background: linear-gradient(135deg,#d8f4ff,#75c7f0); transform: rotateX(90deg) translateZ(calc(var(--scene-size) * .057)); transform-origin: top; clip-path: polygon(0 0,100% 0,78% 100%,0 100%); }.parcel__top span { position: absolute; width: 18%; height: 100%; left: 44%; background: rgba(255,255,255,.62); }.parcel__front { display: grid; place-content: center; gap: 7%; text-align: center; background: linear-gradient(135deg,#2677ff,#1439ca); color: white; box-shadow: inset -12px -12px 24px rgba(5,16,66,.2); transform: translateZ(calc(var(--scene-size) * .057)); }.parcel__front b { width: 2.3rem; height: 2.3rem; display: grid; place-items: center; margin: auto; border: 2px solid rgba(255,255,255,.85); border-radius: 50%; font-size: 1.35rem; }.parcel__front em { font-style: normal; font-size: clamp(.38rem,1.1vw,.58rem); font-weight: 700; letter-spacing: .13em; white-space: nowrap; }.parcel__side { width: 38%; left: auto; background: linear-gradient(180deg,#0b259a,#061568); transform: rotateY(90deg) translateZ(calc(var(--scene-size) * .057)); transform-origin: right; }
.spark { position: absolute; width: .4rem; height: .4rem; border-radius: 50%; background: var(--barely-blue); box-shadow: 0 0 14px var(--barely-blue); animation: sparkle 3s ease-in-out infinite; }.spark--one { top: 18%; left: 22%; }.spark--two { top: 26%; right: 15%; animation-delay: 1s; }.spark--three { bottom: 32%; right: 30%; width: .25rem; height: .25rem; animation-delay: 2s; }.delivery-scene--compact { --scene-size: min(14rem,45vw); }.delivery-scene--compact .scene-glow { opacity: .7; }
@keyframes parcel-float { 0%,100% { transform: translateY(0) rotateX(-13deg) rotateY(-29deg) rotateZ(8deg); } 50% { transform: translateY(-14px) rotateX(-10deg) rotateY(-24deg) rotateZ(5deg); } } @keyframes shadow-float { 0%,100% { transform: scale(1) rotateX(67deg); opacity:.7; } 50% { transform:scale(.8) rotateX(67deg); opacity:.35; } } @keyframes breathe { 50% { transform: scale(1.08); opacity:.7; } } @keyframes pulse { 70% { box-shadow: 0 0 0 14px rgba(23,61,237,0); } 100% { box-shadow:0 0 0 7px rgba(23,61,237,0); } } @keyframes sparkle { 0%,100% { transform:scale(.4); opacity:.25; } 45% { transform:scale(1.2); opacity:1; } } @media (prefers-reduced-motion:reduce) { .delivery-scene *,.delivery-scene { animation:none !important; } }
</style>
